# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install pm2 -g
      - run: |
          - cp ./node_modules/three/build/three.module.js ./src/programs/three.module.js
          - cp ./node_modules/three/examples/jsm/controls/OrbitControls.js ./src/programs/OrbitControls.js
          - cp ./node_modules/three/examples/jsm/loaders/doubleDepthBuffer.js ./src/programs/doubleDepthBuffer.js
          - cp ./node_modules/three/examples/jsm/libs/dat.gui.module.js ./src/programs/dat.gui.module.js
      - run: pm2 start src/server.js --name node-app
