# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install pm2 -g
      - uses: actions/checkout@master
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "./node_modules/three/build/three.module.js, ./node_modules/three/examples/jsm/controls/OrbitControls.js, ./node_modules/three/examples/jsm/libs/dat.gui.module.js"
          target: "./src/programs"
      - run: pm2 start src/server.js --name node-app

        
